### ISSUE TITLE
[BUG] crane export hangs on namespaces with high number of imagestreamtags

### ISSUE THREAD

**Issue by nikita698** [konveyor/crane#110]
**What version of crane are you running, and what are your clutsters+platform**

`crane version`
```
crane:
	Version: v0.0.3
crane-lib:
	Version: v0.0.6
```

Running crane cli and exporting a namespace on OpenShift 4.8.23

**What did you expect to happen?**
The crane export command to complete

**What actually happened?**
The crane command hangs in the `adding resource` stage, the command is stuck when trying to add image stream tags on namespaces with a lot of these objects. The namespace had 2707 image stream tags. When exporting a namespace with a small amount of image stream tags, the command works.
This did not happen on the previous version of crane-lib(v0.0.5). (I used the exact same namespace)

**Please include any relevant logs or errors**
```
DEBU[0005] processing resource: image.openshift.io/v1.ImageStream
INFO[0006] adding resource: imagestreams to the list of GVRs to be extracted
DEBU[0006] processing resource: image.openshift.io/v1.ImageStreamTag
```

**Comment by djzager** [comment]
This appears related to https://github.com/konveyor/crane/commit/94604ca969c2e7c193d2fa00dfebdd5b882d0a13 where we made the update so we could get all of the information associated with imagestreams.

Could you please verify whether `crane export --namespace ${NAMESPACE_WITH_TONS_OF_IMAGESTREAMTAGS}` completes or not, ie. give it as much time as reasonable? We may need to show progress for this case specifically...but it would be really helpful to know if it **ever** completes.

**Comment by nikita698** [comment]
> This appears related to [94604ca](https://github.com/konveyor/crane/commit/94604ca969c2e7c193d2fa00dfebdd5b882d0a13) where we made the update so we could get all of the information associated with imagestreams.
> 
> Could you please verify whether `crane export --namespace ${NAMESPACE_WITH_TONS_OF_IMAGESTREAMTAGS}` completes or not, ie. give it as much time as reasonable? We may need to show progress for this case specifically...but it would be really helpful to know if it **ever** completes.

It completes after roughly 10 to 15 minutes, which is quite unreasonable compared to the old version. If there's no way of making it go quicker, maybe adding a flag that will skip these resources is a solution? I'm not really interested in the image stream tags anyways because the relevant ones are mentioned in the image stream object.

**Comment by djzager** [comment]
ImageStreamTags in the previous version were missing important information from the resource.

I agree that 10-15 minutes is unacceptable. Need to think about how best to handle this...see if there is anything we can do to speed it up.

**Comment by djzager** [comment]
@nikita698 are you able to share a method for creating this scenario with "a high number of imagestreamtags"? Thank you.

I think the easy answer is to allow the user to drop the individual get requests for ImageStreamTags, but want to investigate some more.

**Comment by djzager** [comment]
@nikita698, after discussion with the team, we prefer the solution where we solve the getting rate limited into oblivion versus the new flag. #133 should address the problem

**Comment by jmontleon** [comment]
Just to add, please feel free to comment with results, and reopen if it doesn't adequately address it. Hopefully it takes a good deal less than 10-15 minutes now.
