### ISSUE TITLE
[BUG] No way to specify an alternate transfer-pvc image

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane#116]
**What version of crane are you running, and what are your clutsters+platform**
0.0.4 dev

**What did you expect to happen?**
There's no way to override the transfer-pvc image.

**What actually happened?**
There's no way to override the transfer-pvc (rsync) pod. This means it always pulls from quay.

**Please include any relevant logs or errors**
It looks like crane-lib has a default set that can be overridden, but it is not exposed in crane.

I think we need to roughly approximate the tunnel-api options:
```
     --destination-image string     The container image to use on the destination cluster. Defaults to quay.io/konveyor/openvpn:latest
     --source-image string          The container image to use on the source cluster. Defaults to quay.io/konveyor/openvpn:latest
```

This will be important for downstream as well, since we'll probably have many cases where pulling from quay is not desired or even possible.

**Comment by djzager** [comment]
Need to consider impact to https://github.com/konveyor/crane-operator ... specifically if we need to add "relatedImages" to the CSV.

**Comment by djzager** [comment]
We have [relatedImages for most of these already](https://github.com/konveyor/crane-operator/blob/main/config/manifests/bases/crane-operator.clusterserviceversion.yaml#L55-L63) and logic for [handling image overrides](https://github.com/konveyor/crane-operator/blob/main/controllers/images.go).

You are right...this would just be another on that list.

**Comment by jmontleon** [comment]
--source-image and --destination-image flags are now available. Issues have been opened for relatedImages
