### ISSUE TITLE
[BUG] crane does not return an non-zero exit code when plugins are not found

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane#127]
**What version of crane are you running, and what are your clutsters+platform**
```
crane:
	Version: v0.0.3
crane-lib:
	Version: v0.0.6
```

**What did you expect to happen?**
Crane should have returned an exit code other than 0 and the container should have failed to build.

**What actually happened?**
The build proceeded and pushed without the plugins

**Please include any relevant logs or errors**
```
[3/3] STEP 9/12: RUN crane plugin-manager add OpenShiftPlugin --version v0.0.3
Run "crane plugin-manager list" to list all the available plugins 

time="2022-07-06T20:21:48Z" level=error msg="The plugin OpenShiftPlugin is not found"
--> 525f12999ed
[3/3] STEP 10/12: RUN crane plugin-manager add ImagestreamPlugin
Run "crane plugin-manager list" to list all the available plugins 

time="2022-07-06T20:21:49Z" level=error msg="The plugin ImagestreamPlugin is not found"
```

**Comment by eriknelson** [comment]
@djzager might have exposed a hole in the sync. I think we would have wanted this to show up in jira but I triaged after it was closed. If we still want this to be verified by QE, we need to make sure that it gets an associated triage.. I'll set a TODO to see what we can do about it.

@jmontleon I'm just opening to see if I can trigger the sync.

**Comment by eriknelson** [comment]
Sorry about this @jmontleon, we need to figure out how to enable you to work this way without getting in your way while also makinng sure some kind of a proxy Jira makes its way into that system so it's on QE team's radar for verification, ortherwise they would never see this. I'll thin a bit on this.
 CC: @djzager

**Comment by jmontleon** [comment]
No worries! Test away!
