### ISSUE TITLE
UX fix for transform

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/crane#25]
If a user has an existing transform manifest in their transform dir, no error occurs, and it is not replaced. It may be useful to log a message to the user indicating this, and allow them to re-write the existing manifest with the new transform.

**Comment by sseago** [comment]
From what I recall, if a *new* transform file is generated, then any old ones are overwritten, but if there are no-longer-relevant old transform files, those are left alone (and not looked at). The intent (with the initial implementation) was that if I run transform and then apply, everything generated in the transform step is available for apply, and anything not touched by the transform step is ignored by apply. To support this, we *do* delete whiteout files for resources that are no longer indicated as whiteout.

So I have a couple questions on this:
1) Are you seeing new transforms not being created if there's an old file? If so, that's a bug and we need to fix it.
2) What should we do with other files that already exist prior to running transform? Delete them all? (that would be relatively easy.) Warn on any that exist that we're no longer dealing with? (This is probably not the right approach. We'd have to create a list of files, then identify which ones we overwrote, and then log a warning on anything in the list that wasn't touched again.)

It may be that for the "not relevant to this transform" file problem we want to provide a flag indicating whether or not to delete the directory contents prior to running transform. Perhaps by default it should be false (to lessen the chance of a user accidentally providing a directory that they actually need -- imagine a user choosing the current directory, or their home directory, as a transform dir). Further, perhaps we should only delete files that fit the transform file naming schemes -- so we'd only delete patch files and whiteout files, not other files.

**Comment by shawn-hurley** [comment]
@sseago We were seeing 1.

**Comment by sseago** [comment]
@shawn-hurley Ok, if we're failing to create new transform files as needed, that may be a regression from earlier behavior -- or maybe I didn't test things as I thought I did.  The `os.Create(tfPath)` call *should* create a new file it it doesn't exist or truncate the existing file if it's already there. If it's not doing that, then I'm not sure why.
