### ISSUE TITLE
Publish Versioned Artifacts

### ISSUE THREAD

**Issue by SudoBrendan** [konveyor/crane#31]
Hey everyone! Love this project. I have been recommending it for GitOps as an export tool.

Given the current state of the project, it's difficult to tell what state the software is in. Additionally, for people that don't have golang installed on their local boxes or know anything about it, compiling from source is a huge barrier to entry. Is there a plan to start implementing binary releases for various architectures based on semantically versioned code?

**Comment by shawn-hurley** [comment]
Hello, 

We recently created a release with artifacts https://github.com/konveyor/crane/releases/tag/v0.0.1 

Please note that many of the plugins and other such utilities are not yet built/available but we are working on some enhancements in this space: https://github.com/konveyor/enhancements/pull/41

This enhancement will be superseded IIUC by another engineer shortly if you would like to follow along with that!

Going to close this issue as I believe that the main ask has been completed. Could you re-open if you disagree?
