### ISSUE TITLE
velero vs crane 

### ISSUE THREAD

**Issue by yanivpaz** [konveyor/crane#32]
Hi
what is the difference between this project and Velero?
https://github.com/vmware-tanzu/velero

**Comment by sseago** [comment]
Velero's main purpose is to facilitate backup and restore operations, although it can also be used for migration. Crane's main purpose is workload migration. Current Crane 1.x releases (mig-controller, mig-operator, mig-ui repos under konveyor) use velero as a component of the migration solution. The konveyor/crane repo is for the pre-release work which we're calling "Crane 2.0" and is a complete rewrite which is not based on the complete velero infrastructure, but it does make use of Velero's discovery/export logic. In addition to this, Crane 2.0 will expand beyond simply migrating current workloads to allow for repeatable deployments for the future.

**Comment by shawn-hurley** [comment]
Going to close this issue as I think Scott did a good job answering the question.

If you feel like there is more to be discussed can you please either re-open or add a comment here :) 

Thanks!
