### ISSUE TITLE
Handle namespace mapping

### ISSUE THREAD

**Issue by sseago** [konveyor/crane#54]
One feature that we have in the prior generation of Crane/MTC tools is the ability to migrate a workload to a different namespace on the destination cluster. We need something similar in the new crane workflow. There are a few things that we do in MTC via velero and plugins that we'd need to do here as well. This could all be done relatively easily as a crane plugin. It may be possible to do it via something like kustomize as well, but it would probably be more challenging to do it there, so for the moment I'd recommend a plugin for this.

Here are the things that we're currently dealing with that we also need this plugin (or other implementation) to handle:
1) Modify metadata.namespace if the current namespace is in the mapping.
2) For RoleBindings, subjects, usernames, and groups need to be modified if they reference namespaces that are being remapped
3) For BuildConfigs, imagestream/imagestreamtag references need to be modified if they reference namespaces that are being remapped

Here are some cases which we have in velero plugins that deal with namespace swaps that we probably don't need here:
1) image references (in pods, pod templates, etc.) that reference an internal image or istag within the image path -- this is already handled by the `registry-replacement` arg in the kubernetes plugin.
2) The velero plugin actions for sccs and cluster role bindings -- crane is excluding cluster-scoped resources from scope, so we won't need this here either.

**Comment by eriknelson** [comment]
We currently have a good idea how this should be accomplished, and it's using Kustomize to layer back in cluster specific details such as the target namespace. We have some examples of this in the [crane-runner scenarios](https://github.com/konveyor/crane-runner/blob/main/examples/stateless-app-migration-with-kustomize/README.md) for crane cli. For RHO, I want to make sure that this works as we expect: The workload should migrate into the contextually active namespace that I'm running the wizard from, and the pipeline should handle that.

**Comment by djzager** [comment]
Described how to accomplish this in the stateless application mirror example https://crane-docs.konveyor.io/content/examples/stateless-app-mirror/#apply-manifests-to-destination-cluster
