### ISSUE TITLE
make the developer scripts work with OSX

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/crane#62]
With #56 we added automation for setting up minikube clusters on linux. 

OSX has a different way of networking VMs. In OSX both the VMs would be in the same subnet so we would not require an equivalent of iptables and routing rules.

Similarly in the delete script, we will not require to delete the iptables rules.

**Comment by eriknelson** [comment]
I think this is completed, please create a specific bug report if there is still work to be done here.
