### ISSUE TITLE
[RFE] `transfer-pvc`'s rsync pod names are hardcoded preventing parallelization

### ISSUE THREAD

**Issue by djzager** [konveyor/crane#66]
**What is your persona?**

I'm running a migration using Tekton Pipeline's. I would like to be able to run two `transfer-pvc` commands in parallel but I cannot because `rsync` is the name of the Pod (so only 1 transfer can be happening at a time).

**Comment by eriknelson** [comment]
Closing -- I believe this to have been addressed and we have Jira covering this for RHO.
