### ISSUE TITLE
[BUG] typo in the output of "crane export --help"

### ISSUE THREAD

**Issue by ppremru** [konveyor/crane#71]
**What version of crane are you running, and what are your clutsters+platform**
crane:
	Version: v0.0.3
crane-lib:
	Version: v0.0.5

**What did you expect to happen?**

**What actually happened?**

**Please include any relevant logs or errors**
Typos:
1. Example is mispelled:  "An *eample* is --as-extras key=string1,string2;key2=string3" 
2. Should be "to impersonate"?:  "The group *to impersonation*."
2. Should be "to impersonate"?:  "The user *to impersonation*."

**Comment by apoorvajagtap** [comment]
Hello @ppremru, I have trying to fix this one, So, could you please help with confirmation on point 2 & 3?
I understand, that you expect to have the statement in [#L68](https://github.com/konveyor/crane/blob/main/cmd/export/export.go#L68) modified as following:
`extras requires specifying a user or group to impersonation` ? 

Let me know, if I am misinterpreting. Thanks!

**Comment by eriknelson** [comment]
I believe this has been fixed by #80, thank you @apoorvajagtap !

**Comment by ppremru** [comment]
The change in L68 above is not addressing 2 & 3 in the output of "crane export --help".

At the time this bug was reported, the output looked like this:    (The 3 typos are highlighted below).

Usage:
  crane export [flags]

Flags:
      --as-extras string    The extra info for impersonation can only be used with User or Group but is not required. An **eample** is --as-extras key=string1,string2;key2=string3
      --as-group strings    **The group to impersonation.**   _This should say "The group to impersonate."_
      --as-user string      **The user to impersonation.**   _This should say "The user to impersonate."_
      --context string      The kube context, if empty it will use the current context. If --namespace is set it will take precedence
  -e, --export-dir string   The path where files are to be exported (default "export")
  -h, --help                help for export
  -n, --namespace string    The kube namespace to export.

Global Flags:
      --debug               Debug the command by printing more information
  -f, --flags-file string   Path to input file which contains a yaml representation of cli flags. Explicit flags take precedence over input file values.

.

**Comment by apoorvajagtap** [comment]
@eriknelson i think, though #80 doesn't address 2 & 3, but with the latest changes, we might not need to modify the flag description. As the current output of `crane export --help` is as follows (--as-user option is no longer available/probably replaced by "--as", and description for "--as-group" has been modified already)

```
$  ./crane version                                                                                                            [±main ]
crane:
	Version: v0.0.3
crane-lib:
	Version: v0.0.6

$ ./crane export --help                                                                                                      [±main ]
Export the namespace resources in an output directory

Usage:
  crane export [flags]

Flags:
      --as string                      Username to impersonate for the operation
      --as-extras string               The extra info for impersonation can only be used with User or Group but is not required. An example is --as-extras key=string1,string2;key2=string3
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string               Default cache directory (default "/home/apoorva/.kube/cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -e, --export-dir string              The path where files are to be exported (default "export")
  -h, --help                           help for export
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use

Global Flags:
      --debug               Debug the command by printing more information
  -f, --flags-file string   Path to input file which contains a yaml representation of cli flags. Explicit flags take precedence over input file values.
```
