### ISSUE TITLE
crane plugin-manager list not working as expeceted

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/crane#94]
**What version of crane are you running, and what are your clutsters+platform**
[alpatel@alpatel kafka]$ crane version
crane:
        Version: v0.0.3
crane-lib:
        Version: v0.0.6

OS: linux, source cluster k3d, destination OpenShift

**What did you expect to happen?**
`$ crane plugin-manager list` command should list the Plugins available

**What actually happened?**
```
[alpatel@alpatel kafka]$ crane plugin-manager list
ERRO[0000] Error reading ImageStreamPlugin plugin manifest located at https://github.com/konveyor/crane-plugins/raw/main/plugins/ImageStream/index.yaml - Error: error
converting YAML to JSON: yaml: line 163: mapping values are not allowed in this context
```

**Please include any relevant logs or errors**
I think the urls here https://github.com/konveyor/crane-plugins/blob/main/index.yaml#L5 might be wrong

**Comment by eriknelson** [comment]
Considering this closed by #19 , @JaydipGabani could you confirm?
