### ISSUE TITLE
remove duplicate plugin name entries from manifests

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/crane#95]
**What is your persona?**
plugin publisher

**What is your story / use case?**

As a plugin publisher, I would like to configure the name of the plugin once, instead of twice https://github.com/konveyor/crane-plugins/blob/main/index.yaml#L4 and https://github.com/alaypatel07/crane-plugins/blob/main/index.yaml#L4 to avoid typos

What is your specific intent, not necessarily the feature you want, but what are
you trying to achieve?

Reduce bugs caused due to human errors during publishing a plugin

How does your immediate need fit into your bigger picture? What's the overall
benefit?

This makes sure that `crane plugin-manager list` and `crane plugin-manager add` work with the same name

**Do you have a suggestion for implementation?**

It's important to decouple implementation from the story and use case itself,
but do you have a proposed solution that would serve your needs?

**Comment by alaypatel07** [comment]
this is evident in fix https://github.com/konveyor/crane-plugins/pull/19

**Comment by eriknelson** [comment]
Also considering this closed by #19 , @JaydipGabani need confirmation.
